version: "3.7"
name: "myproject"
services:
  service-a:
    image: docker.io/library/nginx:stable-alpine-slim
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - /var/volumes/service-a:/config
      - storage:/storage
    deploy:
      resources:
        reservations:
          cpus: "0.5"
    labels:
      - 'compose2nix.systemd.service.Restart="no"'
      - "compose2nix.systemd.service.RuntimeMaxSec=360"
      - "compose2nix.systemd.unit.Description=This is the service-a container!"
    restart: unless-stopped
  service-b:
    image: docker.io/library/nginx:stable-alpine-slim
    container_name: service-b
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - /var/volumes/service-b:/config
      - storage:/storage
    labels:
      - "compose2nix.systemd.unit.AllowIsolate=no"
      - "compose2nix.systemd.service.RuntimeMaxSec=360"
    depends_on:
      - service-a
    restart: on-failure:3

networks:
  something:
    labels:
      - "test-label=okay"

volumes:
  storage:
    name: storage
    driver_opts:
      type: none
      device: /mnt/media
      o: bind
