name: Test

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21'
    - run: go version
    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: coverage.out
  check-nix-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build
    - run: nix flake check
